### ISSUE TITLE
Do not remove all new lines

### ISSUE THREAD

**Issue by erickpires** [Taritsyn/JSMin.NET#1]
I have a use case where I need to remove all comments and excessive spaces and new lines, but I need to have one new line after every line of the original script (a.k.a. two or more lines can't become only one line).
For example, the following code:
```
// This is a test

var   a = 1; /* Another test */


console.log(a);
```

Must become:
```
var a=1;
console.log(a);
```

I searched the repository for a way to configure JSMin to do this, but found none. Is this possible?

**Comment by Taritsyn** [comment]
Hello, Erick!

> I searched the repository for a way to configure JSMin to do this, but found none. Is this possible?

It's impossible, there are no settings at all, because this library is an exact port of the [Douglas Crockford's JSMin](http://github.com/douglascrockford/JSMin). If you need advanced settings, then use a [NUglify](https://github.com/xoofx/NUglify).

**Comment by erickpires** [comment]
I was using NUglify, but it has a lot of issues with `async` syntax and I decided to use JSMin instead.

Would you accept a PR if I implement a multi-line mode?

**Comment by Taritsyn** [comment]
> Would you accept a PR if I implement a multi-line mode?

No. Offer this feature to author of [original library](https://github.com/douglascrockford/JSMin), and then I'm porting it. 

> I was using NUglify, but it has a lot of issues with `async` syntax and I decided to use JSMin instead.

There has recently corrected these errors. It is more logical to solve problems with new standards in the NUglify library.

I also recommend to ask about the fate of the [Microsoft Ajax Minifier](https://github.com/Microsoft/ajaxmin).

**Comment by erickpires** [comment]
> There has recently corrected these errors. It is more logical to solve problems with new standards in the NUglify library.

No, not all the bugs have been fixed, a friend of mine has fixed some of them and made a PR, but this code is not included in any release and we keep finding more bugs.

Thank you anyway.
